<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>false</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.16" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.16" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.16" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RiivolutionIsoBuilder.Core\RiivolutionIsoBuilder.Core.csproj" />
  </ItemGroup>
</Project>
